# Generated by Django 2.1.1 on 2018-09-17 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_details', models.TextField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_mine.Account', verbose_name='related account')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('status_description', models.TextField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_mine.Account', verbose_name='related account')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_title', models.CharField(max_length=100)),
                ('ticket_details', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_mine.Project', verbose_name='related project')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_mine.Status', verbose_name='project status')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_mine.Type', verbose_name='project type'),
        ),
    ]
